name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_MYDOCKER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
           image: bahrami127/marketking
           tags: v1, latest
           registry: registry-url.io
           dockerfile: Dockerfile.ci
           username: ${{ secrets.DOCKER_MYDOCKER }}
           password: ${{ secrets.DOCKER_PASSWORD }}