name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_MYDOCKER }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}   # Your Docker Hub password

      # Step 3: Build and push the Docker image
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: bahrami127/marketking  # Image name on Docker Hub
          tags: v1, latest  # Tags for the image
          dockerfile: Dockerfile.ci  # Path to the Dockerfile
